project/accounting/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from .views import AccountTransactionEntry, AccountDetail, AccountPinInfo, AccountUpdate
from .views import EntryUpdate
from .views import OwnerDetail, OwnerCreate, OwnerUpdate, OwnerDelete
from .views import LeaseDetail, LeaseCreate, LeaseUpdate, LeaseDelete
from .views import TenantDetail, TenantUpdate, TenantRemove, TenantDelete
from .views import VehicleDetail, VehicleUpdate, VehicleRemove, VehicleDelete
from .views import GenerateReports, ListReportFiles
from .reports import DelinquencyReport, TransactionsReport, StatementReport
from .reports import AccountTrailReport, ExportReport, LeaseReport, IncomeReport, AccountAuditReport
from .reports import EMailStatements
from .reports import cancel_report
from .tasks import apply_assessments, apply_late_fees

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Account Views.
    url(r'^$', AccountTransactionEntry.as_view(), name='list'),
    url(r'^enter/$', AccountTransactionEntry.as_view(), name='enter'),
    url(r'^account/(?P<pk>\d+)/enter/$', AccountTransactionEntry.as_view(), name='account_enter'),
    url(r'^account/$', RedirectView.as_view(url='/accounting', permanent=False), name='list'),
    url(r'^account/(?P<pk>\d+)/$', AccountDetail.as_view(), name='detail'),
    url(r'^account/(?P<pk>\d+)/update/$', AccountUpdate.as_view(), name='update'),
    url(r'^account/(?P<pk>\d+)/pin/(?P<pin>\d{2}-\d{2}-\d{3}-\d{3}-\d{4})/$', AccountPinInfo.as_view(), name='pin_info'),

    # Entry Views.
    url(r'^entry/(?P<pk>\d+)/update/$', EntryUpdate.as_view(), name='entry_update'),

    # Owner Views.
    url(r'^owner/(?P<pk>\d+)/$', OwnerDetail.as_view(), name='owner_detail'),
    url(r'^owner/add/(?P<acct_id>[BCP][0-9]{4}[1-6]{1})/$', OwnerCreate.as_view(), name='owner_add'),
    url(r'^owner/(?P<pk>\d+)/update/(?P<acct_pk>\d+)/$', OwnerUpdate.as_view(), name='owner_update'),
    url(r'^owner/(?P<pk>\d+)/delete/(?P<acct_pk>\d+)/$', OwnerDelete.as_view(), name='owner_delete'),
    url(r'^owner/(?P<pk>\d+)/delete/$', OwnerDelete.as_view(), name='owner_delete'),

    # Lease Views.
    url(r'^lease/(?P<pk>\d+)/$', LeaseDetail.as_view(), name='lease_detail'),
    url(r'^lease/add/(?P<acct_pk>\d+)/$', LeaseCreate.as_view(), name='lease_add'),
    url(r'^lease/(?P<pk>\d+)/update/(?P<acct_pk>\d+)/$', LeaseUpdate.as_view(), name='lease_update'),
    url(r'^lease/(?P<pk>\d+)/delete/(?P<acct_pk>\d+)/$', LeaseDelete.as_view(), name='lease_delete'),

    # Tenant Views.
    url(r'^tenant/(?P<pk>\d+)/$', TenantDetail.as_view(), name='tenant_detail'),
    url(r'^tenant/(?P<pk>\d+)/update/(?P<acct_pk>\d+)/$', TenantUpdate.as_view(), name='tenant_update'),
    url(r'^tenant/(?P<pk>\d+)/remove/(?P<acct_pk>\d+)/$', TenantRemove.as_view(), name='tenant_remove'),
    url(r'^tenant/(?P<pk>\d+)/delete/$', TenantDelete.as_view(), name='tenant_delete'),

    # Vehicle Views.
    url(r'^vehicle/(?P<pk>\d+)/$', VehicleDetail.as_view(), name='vehicle_detail'),
    url(r'^vehicle/(?P<pk>\d+)/update/(?P<acct_pk>\d+)/$', VehicleUpdate.as_view(), name='vehicle_update'),
    url(r'^vehicle/(?P<pk>\d+)/remove/(?P<acct_pk>\d+)/$', VehicleRemove.as_view(), name='vehicle_remove'),
    url(r'^vehicle/(?P<pk>\d+)/delete/$', VehicleDelete.as_view(), name='vehicle_delete'),

    # Report Views.
    url(r'^reports/$', GenerateReports.as_view(), name='generate_reports'),
    url(r'^reports/list/(?P<type>\w+)/$', ListReportFiles.as_view(), name='list_report_files'),

    url(r'^report/delinquency/$', DelinquencyReport.as_view(), name='delinquency_report'),
    url(r'^report/delinquency/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<date>\d{4}-\d{2}-\d{2})/$', DelinquencyReport.as_view(), name='delinquency_report'),

    url(r'^report/transaction/$', TransactionsReport.as_view(), name='transaction_report'),
    url(r'^report/transaction/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<type>\d{1})/(?P<bDate>\d{4}-\d{2}-\d{2})/(?P<eDate>\d{4}-\d{2}-\d{2})/$', TransactionsReport.as_view(), name='transaction_report'),

    url(r'^report/statement/$', StatementReport.as_view(), name='statement_report'),
    url(r'^report/statement/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<date>\d{4}-\d{2}-\d{2})/$', StatementReport.as_view(), name='statement_report'),
    url(r'^report/statement/(?P<date>\d{4}-\d{2}-\d{2})/(?P<accountId>\w+)/$', StatementReport.as_view(), name='statement_report'),
    url(r'^report/statement/(?P<date>\d{4}-\d{2}-\d{2})/(?P<accountId>\w+)/(?P<type>\w+)/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/$', StatementReport.as_view(), name='statement_report'),
    url(r'^report/statement/email/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/$', EMailStatements.as_view(), name='email_statements'),

    url(r'^report/income/$', IncomeReport.as_view(), name='income_report'),
    url(r'^report/income/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<type>\d{1})/(?P<bDate>\d{4}-\d{2}-\d{2})/(?P<eDate>\d{4}-\d{2}-\d{2})/$', IncomeReport.as_view(), name='income_report'),

    url(r'^report/account_trail/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<date>\d{4}-\d{2}-\d{2})/$', AccountTrailReport.as_view(), name='account_trail_report'),
    url(r'^report/account_trail/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<date>\d{4}-\d{2}-\d{2})/(?P<accountId>\w+)/$', AccountTrailReport.as_view(), name='account_trail_report'),

    url(r'^report/account_audit_report/$', AccountAuditReport.as_view(), name='account_audit_report'),
    url(r'^report/account_audit_report/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<bDate>\d{4}-\d{2}-\d{2})/(?P<eDate>\d{4}-\d{2}-\d{2})/$', AccountAuditReport.as_view(), name='account_audit_report'),

    url(r'^report/export/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/$', ExportReport.as_view(), name='export_report'),

    url(r'^report/lease/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<type>expired|fha|vos)/$', LeaseReport.as_view(), name='lease_report'),
    url(r'^report/lease/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/(?P<type>expired|fha|vos)/(?P<date>\d{4}-\d{2}-\d{2})/$', LeaseReport.as_view(), name='lease_report'),

    # Cancel report generation.
    url(r'^report/cancel/(?P<reportType>\w+)/(?P<reqId>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})/$', cancel_report),

    # Common tasks.
    url(r'^apply_assessments/$', apply_assessments),
    url(r'^apply_late_fees/$', apply_late_fees),
)

project/hiddenpond/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from haystack.views import SearchView
from .search import SearchResults, SimpleSearch 
from .media import serve_media, delete_media, serve_log
from registration.views import RegistrationView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Add django-inspectional-registration urls.
    url('^user/', include('registration.urls')),

    url(r'^login/$','django.contrib.auth.views.login'),
    url(r'^logout/$','django.contrib.auth.views.logout',{'next_page':'/'}),

    url(r'^$', login_required(TemplateView.as_view(template_name='index.html')),name='home'),

    # accounting app URLs.
    url(r'^accounting/', include('accounting.urls', namespace='accounts')),

    # payment app URLs.
    url(r'^payment/', include('payment.urls', namespace='accounts')),

    url(r'^report_error/', TemplateView.as_view(template_name='report_error.html')),

    #url(r'^search/',SimpleSearch.as_view(),name='search_results'),
    url(r'^search/',SearchResults(),name='haystack_search'),
    #url(r'^search/',SearchView(load_all=False)),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Serve static media files.
    url(r'^media/(?P<mediaType>\w+)/(?P<subType>\w+)/(?P<filename>\w+)\.(?P<fileExtension>\w+)$', serve_media),

    # Delete static media files
    url(r'^delete/media/(?P<mediaType>\w+)/(?P<subType>\w+)/(?P<filename>\w+)\.(?P<fileExtension>\w+)$', delete_media),

    # Serve the website log
    url(r'^log/$', serve_log),
)

"""
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

project/tasks/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from .views import AccountList

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^create_task/$', AccountList.as_view(), name='create_task'),
    url(r'^view_open_tasks/$', AccountList.as_view(), name='open_tasks'),
    url(r'^view_completed_tasks/$', AccountList.as_view(), name='completed_tasks'),
    url(r'^mark_complete/$', AccountList.as_view(), name='mark_complete'),
    url(r'^edit_desc/$', AccountList.as_view(), name='edit_desc'),
    url(r'^edit_prio/$', AccountList.as_view(), name='edit_prio'),
)

project/accounting/forms.py
from django import forms
from django.conf import settings
from django.forms import ModelForm
from localflavor.us.forms import USZipCodeField
from .models import Account, Entry, Category, Owner, Lease, Tenant, Vehicle, Report
import logging
import sys

logger = logging.getLogger(__name__)

##############################################################################
class AccountEntryForm(forms.Form):
    category_choices = []
    try:
        categories = Category.objects.all()
        category_choices = [(o.name, o.type) for o in categories if categories]
    except Exception,e:
        logging.exception(e)
    amount = forms.DecimalField()
    memo = forms.CharField()
    category = forms.ChoiceField(choices=category_choices)
    date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    accounts = forms.BooleanField(
        error_messages={ 
           'required':'Please specify one more more accounts',
        })

    def clean(self):
        cleaned_data = super(AccountEntryForm, self).clean()
        amount = cleaned_data.get('amount')
        category = cleaned_data.get('category')
        if amount and category:
            category_type = Category.objects.get(name=category).type
            if (amount < 0 and category_type == Category.CHARGE or
                amount > 0 and category_type == Category.PAYMENT):
                msg = u"Please enter a positive amount for a charge, negative for a payment!"
                self._errors['amount'] = self.error_class([msg])
                self._errors['category'] = self.error_class([msg])
                del cleaned_data['amount']
                del cleaned_data['category']

        return cleaned_data

##############################################################################
class AccountForm(ModelForm):
    class Meta:
        model = Account
        exclude = ['balance','acct_id','orig_id','pin','unit']

##############################################################################
class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = ['memo']

##############################################################################
class OwnerForm(ModelForm):
    zip = USZipCodeField()

    class Meta:
        model = Owner
        fields = '__all__'

##############################################################################
class Html5DateInput(forms.DateInput):
    input_type = 'date'

##############################################################################
class TenantForm(ModelForm):
    class Meta:
        model = Tenant
        fields = '__all__'

##############################################################################
class LeaseForm(ModelForm):
    class Meta:
        model = Lease
        fields = '__all__'

##############################################################################
class VehicleForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = '__all__'

##############################################################################
class ReportForm(ModelForm):
    date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)

    class Meta:
        model = Report 
        fields = '__all__'

project/accounting/templates/accounting/account_list.html
{% extends "base.html" %}

{% load humanize staticfiles %}

{% block title %}Accounts{% endblock %}

{% block page_title %}{% endblock page_title %}

{% block extra_css %}

{% if debug %}
    <link href="{% static 'css/dataTables.bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/buttons.bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/buttons.dataTables.css' %}" rel="stylesheet"/>

    <link href="{% static 'css/bootstrap-datetimepicker.css' %}" rel="stylesheet"/>
{% else %}
    <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/buttons.dataTables.min.css' %}" rel="stylesheet"/>

    <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endif %}

{% endblock extra_css %}

{% block content %}

{% if account_list %}

    {% include "accounting/entry_form.html" %}

    <table id="accounts-table"
           class="table table-bordered table-hover table-condensed table-striped dataTable">
        <thead>
            <tr>
                <th class="text-center">
                    <input id="select_all_head" 
                           name="select_all_head"
                           class="selectedId" 
                           title="Select All" 
                           type="checkbox"/>
                </th>
                <th class="text-center" data-defaultsort="asc">Account</th> 
                <th class="text-center">Address</th>
                <th class="text-center">Balance</th> 
                <th class="text-center">Info</th>
            </tr>
        </thead>

        <tbody id="accounts_body">
            {% for account in account_list %}
            <tr>
                <td class="text-center">
                    <input type="checkbox" 
                           class="selectedId" 
                           title="Select {{ account.acct_id }}"
                           name="accounts"
                           value="{{ account.acct_id }}"
                           id="select_{{ account.acct_id }}"/>
                </td>
                <td class="text-center">
                    <a title="History for {{ account.acct_id }}" 
                       href="{% url 'accounts:detail' account.id %}">
                        {{ account.acct_id }} <span style="font-size: 0.65em;">/ {{ account.orig_id }}</span>
                    </a>
                </td>
                <td class="text-center">{{ account.unit_address }} Apt {{ account.unit_number }}</td>
                <td class="text-center">
                    {% with balance=account.balance %}
                    <a id="{{account.acct_id}}" title="History for {{ account.acct_id }}" 
                       style="color:{% if balance <= 0 %} green {% else %} red {% endif %}"
                       href="{% url 'accounts:detail' account.id %}"><b>{{ balance|floatformat:2|intcomma }}</b></a>
                    {% endwith %}
                </td>
                <td class="text-center">
                    <a title="Owner Info" href="{% url 'accounts:update' account.id %}#owners">Owner</a> /
                    <a title="Lease Info" href="{% url 'accounts:update' account.id %}#lease">Tenant</a> /
                    <a title="Vehicle Info" href="{% url 'accounts:update' account.id %}#vehicles">Vehicle</a>
              </td>
            </tr>
            {% endfor %}
        </tbody>

        <tfoot>
            <tr>
                <th class="text-center">
                    <input id="select_all_foot" 
                           name="select_all_foot"
                           class="selectedId" 
                           title="Select All" 
                           type="checkbox"/>
                </th>
                <th class="text-center" data-defaultsort="asc">Account</th>
                <th class="text-center">Address</th>
                <th class="text-center">Balance</th>
                <th class="text-center">Owner</th>
            </tr>
        </tfoot>
    </table>

{% else %}
    {% if form.errors %}
        {{ form.errors }}
    {% else %}
        <p>No accounts are available.</p>
    {% endif %}
{% endif %}

{% endblock content %}

{% block extra_js %}

{% if debug %}
    <script src="{% static 'js/bootbox.js' %}"></script>

    <script src="{% static 'js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'js/dataTables.buttons.js' %}"></script>
    <script src="{% static 'js/buttons.bootstrap.js' %}"></script>
    <script src="{% static 'js/buttons.html5.js' %}"></script>
    <script src="{% static 'js/buttons.print.js' %}"></script>

    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>

    <script src="{% static 'js/accounts/csrf.js' %}"></script>
    <script src="{% static 'js/accounts/naturalSort.js' %}"></script>
    <script src="{% static 'js/accounts/account_list.js' %}"></script>
    <script src="{% static 'js/accounts/entry_form.js' %}"></script>
{% else %}
    <script src="{% static 'js/bootbox.min.js' %}"></script>

    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/buttons.print.min.js' %}"></script>

    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>

    <script src="{% static 'js/accounts/csrf.min.js' %}"></script>
    <script src="{% static 'js/accounts/naturalSort.min.js' %}"></script>
    <script src="{% static 'js/accounts/account_list.min.js' %}?ver=1.0"></script>
    <script src="{% static 'js/accounts/entry_form.min.js' %}"></script>
{% endif %}

{% endblock extra_js %}

project/accounting/templates/accounting/lease_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Delete {{ lease }}{% endblock %}

{% block page_title %}{% endblock page_title %}

{% block content %}

<form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}
    <div class="form-group">
        Are you sure you want to delete {{ lease }}? 
    </div>
    <div class="form-group">
        <input type="hidden" name="post" value="yes" />
        <input class="btn btn-success" type="submit" value="Yes, I'm sure" />
        <a class="btn btn-danger" href="javascript:history.back()">Cancel</a>
    </div>
</form>

{% endblock content %}

project/accounting/templates/accounting/lease_tenant_form.html
{% load extras %}

<form id="tenant_form" enctype="multipart/form-data" class="form-horizontal" role="form" action="" method="post">
    {% csrf_token %}
    {% for hidden in lease_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for f in lease_form.visible_fields %}
        <div class="form-group" {% if f.name == "account" %} style="display:none" {% endif %}>
            <label class="col-sm-2 control-label" for="{{ f.id_for_label }}">
                {{ f.label }}
            </label>
            <div class="col-sm-6">
                {{ f.errors }}
                {{ f|addcss:"form-control" }}
                {{ f.help_text }}
            </div>
        </div>
    {% endfor %}

    {% if False %}
    {{ lease_formset.management_form }}
    {% for form in lease_formset %}
        <div class="tenant_container">
            <div class="panel panel-default">
                <div class="panel-heading">
                   Tenant: {{ form.instance }} 
                </div>
                <div class="panel-body">
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    <div class="form-group">
                        <label class="col-sm-2 control-label" 
                               title="Select an existing tenant or enter new tenant info below"
                               id="existing_tenant_id_label"
                               for="existing_tenant_id">
                            <i>Existing tenant:</i>
                        </label>

                        <div class="col-sm-6">
                            <select class="form-control" 
                                    title="Select an existing tenant or enter new tenant info below"
                                    data-toggle="tooltip"
                                    placeholder="Select an existing tenant"
                                    id="existing_tenant_id" 
                                    name="existing_tenant_id">
                                <option value=0 default selected>----------------------------</option>
                                {% for tenant in tenants %}
                                <option value={{tenant.id}}>{{ tenant }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    {% for f in form.visible_fields %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="{{ f.id_for_label }}">
                                {{ f.label }}
                            </label>
                            <div class="col-sm-6">
                                {{ f.errors }}
                                {{ f|addcss:"form-control" }}
                                {{ f.help_text }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}
    {% endif %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input class="btn btn-success" type="submit" name="add_lease" value="Update Lease" />
            <a class="btn btn-danger" href="javascript:history.back()">Cancel</a>
        </div>
    </div>
</form>

project/accounting/templates/accounting/owner_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Delete {{ owner }}{% endblock %}

{% block page_title %}{% endblock page_title %}

{% block content %}

<form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}
    <div class="form-group">
        {% if account.acct_id %}
            Are you sure you want to remove '<b>{{ owner }}</b>' from account <b>{{ account.acct_id }}</b>?
        {% else %}
            Are you sure you want to delete '<b>{{ owner }}</b>'?
        {% endif %}
    </div>
    <div class="form-group">
        <input type="hidden" name="post" value="yes" />
        <input class="btn btn-success" type="submit" value="Yes, I'm sure" />
        <a class="btn btn-danger" href="javascript:history.back()">Cancel</a>
    </div>
</form>

{% endblock content %}

project/accounting/templates/accounting/task_result.html
{% extends "base.html" %}

{% load humanize staticfiles %}

{% block title %}{{title}}{% endblock title %}

{% block page_title %} {% endblock page_title %}

{% block extra_css %}

{% endblock extra_css %}

{% block content %}

<div class="alert alert-{{result|default_if_none:'info'}}">
    <div class="alert alert-{{result|default_if_none:'info'}}">
        {{message}}
    </div>
    {% if accounts %}
    <div class="panel panel-default">
        <div class="panel-heading">
            Late Accounts
        </div>
        <div class="panel-body">
            <table class="table table-no-border table-condensed table-hover table-striped">
                <thead>
                    <tr>
                        <th>Account</th>
                        <th>Balance</th>
                        <th>Owner</th>
                    </tr>
                </thead>
                <tbody>
                {% for account in accounts %}
                <tr>
                    <td>
                        <a href="{{account.get_absolute_url}}">{{account.acct_id}} / <span style="font-size: 0.65em;">{{account.orig_id}}</span></a>
                    </td>
                    <td>
                        ${{account.balance|floatformat:2|intcomma}}
                    </td>
                    <td>
                        {% with owner=account.owner_set.first %}
                        <a href="{{owner.get_absolute_url}}">{{owner}}</a>
                        {% endwith %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock content %}

project/accounting/templates/accounting/tenant_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Delete {{ tenant }}{% endblock %}

{% block page_title %}{% endblock page_title %}

{% block content %}

<form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}
    <div class="form-group">
        Are you sure you want to delete {{ tenant }}{% if account %} from {{ account.acct_id }}{% endif %}?
    </div>
    <div class="form-group">
        <input type="hidden" name="post" value="yes" />
        <input class="btn btn-success" type="submit" value="Yes, I'm sure" />
        <a class="btn btn-danger" href="javascript:history.back()">Cancel</a>
    </div>
</form>

{% endblock content %}

project/accounting/templates/accounting/tenant_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ tenant }}{% endblock %}

{% block page_title %} {% endblock page_title %}

{% block extra_css %}

<link href="{% static 'css/dataTables.bootstrap.css' %}" rel="stylesheet">

{% endblock extra_css %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">Tenant Info</div>
    <div class="panel-body">
        <table class="table table-bordered table-condensed table-striped dataTable">
            <tr>
                <td><b>First Name:</b></td><td>{{ tenant.first_name }}</td>
            </tr>
            <tr>
                <td><b>Last Name:</b></td><td>{{ tenant.last_name }}</td>
            </tr>
            <tr>
                <td><b>Home Phone:</b></td><td><a href="tel:{{tenant.home_phone}}">{{ tenant.home_phone }}</a></td>
            </tr>
            <tr>
                <td><b>Cell Phone:</b></td><td><a href="tel:{{tenant.cell_phone}}">{{ tenant.cell_phone }}</a></td>
            </tr>
            <tr>
                <td><b>E-mail:</b></td><td><a href="mailto:{{tenant.email}}">{{ tenant.email }}</a></td>
            </tr>
            <tr>
                <td><b>Unit Address:</b></td><td>{{ tenant.lease.account.unit_address }} Apt {{ tenant.lease.account.unit_number }}</td>
            </tr>
            <tr>
                <td><b>Is a Relative of the Owner?</b></td>
                <td> {{ tenant.is_owners_relative }} </td>
            </tr>
            <tr>
                <td><b>Account:</b>
                <td>
                    {% if tenant.lease %}
                        <a href="{% url 'accounts:detail' tenant.lease.account.id  %}">{{ tenant.lease.account.acct_id }}</a>
                    {% else %}
                        None
                    {% endif %}
                </td>
            </tr>
        </table>
        
        {% if user.is_staff %}
            {% if tenant.lease %}
                <a class="btn btn-primary" href="{% url 'accounts:tenant_update' tenant.id tenant.lease.account.id %}">Edit</a>
            {% else %}
                <a class="btn btn-warning" href="{% url 'accounts:tenant_delete' tenant.id %}">Delete Tenant</a>
            {% endif %}
            <a class="btn btn-danger"  href="javascript:history.back()">Cancel</a>
        {% endif %}
    </div>
</div>

{% endblock content %}